# Server Configuration
server.port=${PORT:8080}

# Database Connection Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/bike_parts_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:0211}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Custom JWT Security Configurations
# Secret is a 512-bit hex key
app.jwt.secret=9a67a86c7cfb44b82d302b1f8ef447b9c9f05a10ab56be30455088f72df2ef193c78d4511ef5a5b51b34adfaec3a30a1bf6f78810b42de6f3d9e03bb0e0d5921
app.jwt.expiration-ms=86400000

# Logging Configuration
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=ERROR

# Spring Mail SMTP Configuration (Gmail SMTP example)
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
